// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreTask.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fio = "Author_1"
                        },
                        new
                        {
                            Id = 2,
                            Fio = "Author_2"
                        },
                        new
                        {
                            Id = 3,
                            Fio = "Author_3"
                        },
                        new
                        {
                            Id = 4,
                            Fio = "Author_4"
                        },
                        new
                        {
                            Id = 5,
                            Fio = "Author_5"
                        },
                        new
                        {
                            Id = 6,
                            Fio = "Author_6"
                        },
                        new
                        {
                            Id = 7,
                            Fio = "Author_7"
                        },
                        new
                        {
                            Id = 8,
                            Fio = "Author_8"
                        },
                        new
                        {
                            Id = 9,
                            Fio = "Author_9"
                        },
                        new
                        {
                            Id = 10,
                            Fio = "Author_10"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 4
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 5
                        },
                        new
                        {
                            AuthorsId = 8,
                            BooksId = 6
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 7
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 8
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 9
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 10
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 11
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 12
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 13
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 14
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 15
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 16
                        },
                        new
                        {
                            AuthorsId = 9,
                            BooksId = 17
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 18
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 19
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 20
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 21
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 22
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 23
                        },
                        new
                        {
                            AuthorsId = 9,
                            BooksId = 24
                        },
                        new
                        {
                            AuthorsId = 8,
                            BooksId = 25
                        },
                        new
                        {
                            AuthorsId = 8,
                            BooksId = 26
                        },
                        new
                        {
                            AuthorsId = 8,
                            BooksId = 27
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 28
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 29
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 30
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 31
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 32
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 33
                        },
                        new
                        {
                            AuthorsId = 9,
                            BooksId = 34
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 35
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 36
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 37
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 38
                        },
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 39
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 40
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 41
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 42
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 43
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 44
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 45
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 46
                        },
                        new
                        {
                            AuthorsId = 9,
                            BooksId = 47
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 48
                        });
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            PublisherId = 4,
                            Title = "Book_$1"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 1,
                            PublisherId = 2,
                            Title = "Book_$2"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            PublisherId = 3,
                            Title = "Book_$3"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 1,
                            PublisherId = 1,
                            Title = "Book_$4"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 2,
                            PublisherId = 3,
                            Title = "Book_$5"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 2,
                            PublisherId = 2,
                            Title = "Book_$6"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 2,
                            PublisherId = 3,
                            Title = "Book_$7"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 2,
                            PublisherId = 3,
                            Title = "Book_$8"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 3,
                            PublisherId = 3,
                            Title = "Book_$9"
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 3,
                            PublisherId = 5,
                            Title = "Book_$10"
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 3,
                            PublisherId = 1,
                            Title = "Book_$11"
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 3,
                            PublisherId = 1,
                            Title = "Book_$12"
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 4,
                            PublisherId = 1,
                            Title = "Book_$13"
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 4,
                            PublisherId = 2,
                            Title = "Book_$14"
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 4,
                            PublisherId = 1,
                            Title = "Book_$15"
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 4,
                            PublisherId = 4,
                            Title = "Book_$16"
                        },
                        new
                        {
                            Id = 17,
                            GenreId = 5,
                            PublisherId = 5,
                            Title = "Book_$17"
                        },
                        new
                        {
                            Id = 18,
                            GenreId = 5,
                            PublisherId = 2,
                            Title = "Book_$18"
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 5,
                            PublisherId = 1,
                            Title = "Book_$19"
                        },
                        new
                        {
                            Id = 20,
                            GenreId = 5,
                            PublisherId = 3,
                            Title = "Book_$20"
                        },
                        new
                        {
                            Id = 21,
                            GenreId = 6,
                            PublisherId = 1,
                            Title = "Book_$21"
                        },
                        new
                        {
                            Id = 22,
                            GenreId = 6,
                            PublisherId = 3,
                            Title = "Book_$22"
                        },
                        new
                        {
                            Id = 23,
                            GenreId = 6,
                            PublisherId = 2,
                            Title = "Book_$23"
                        },
                        new
                        {
                            Id = 24,
                            GenreId = 6,
                            PublisherId = 3,
                            Title = "Book_$24"
                        },
                        new
                        {
                            Id = 25,
                            GenreId = 7,
                            PublisherId = 4,
                            Title = "Book_$25"
                        },
                        new
                        {
                            Id = 26,
                            GenreId = 7,
                            PublisherId = 4,
                            Title = "Book_$26"
                        },
                        new
                        {
                            Id = 27,
                            GenreId = 7,
                            PublisherId = 1,
                            Title = "Book_$27"
                        },
                        new
                        {
                            Id = 28,
                            GenreId = 7,
                            PublisherId = 2,
                            Title = "Book_$28"
                        },
                        new
                        {
                            Id = 29,
                            GenreId = 8,
                            PublisherId = 2,
                            Title = "Book_$29"
                        },
                        new
                        {
                            Id = 30,
                            GenreId = 8,
                            PublisherId = 3,
                            Title = "Book_$30"
                        },
                        new
                        {
                            Id = 31,
                            GenreId = 8,
                            PublisherId = 5,
                            Title = "Book_$31"
                        },
                        new
                        {
                            Id = 32,
                            GenreId = 8,
                            PublisherId = 3,
                            Title = "Book_$32"
                        },
                        new
                        {
                            Id = 33,
                            GenreId = 9,
                            PublisherId = 2,
                            Title = "Book_$33"
                        },
                        new
                        {
                            Id = 34,
                            GenreId = 9,
                            PublisherId = 1,
                            Title = "Book_$34"
                        },
                        new
                        {
                            Id = 35,
                            GenreId = 9,
                            PublisherId = 4,
                            Title = "Book_$35"
                        },
                        new
                        {
                            Id = 36,
                            GenreId = 9,
                            PublisherId = 1,
                            Title = "Book_$36"
                        },
                        new
                        {
                            Id = 37,
                            GenreId = 10,
                            PublisherId = 3,
                            Title = "Book_$37"
                        },
                        new
                        {
                            Id = 38,
                            GenreId = 10,
                            PublisherId = 2,
                            Title = "Book_$38"
                        },
                        new
                        {
                            Id = 39,
                            GenreId = 10,
                            PublisherId = 5,
                            Title = "Book_$39"
                        },
                        new
                        {
                            Id = 40,
                            GenreId = 10,
                            PublisherId = 1,
                            Title = "Book_$40"
                        },
                        new
                        {
                            Id = 41,
                            GenreId = 11,
                            PublisherId = 3,
                            Title = "Book_$41"
                        },
                        new
                        {
                            Id = 42,
                            GenreId = 11,
                            PublisherId = 4,
                            Title = "Book_$42"
                        },
                        new
                        {
                            Id = 43,
                            GenreId = 11,
                            PublisherId = 2,
                            Title = "Book_$43"
                        },
                        new
                        {
                            Id = 44,
                            GenreId = 11,
                            PublisherId = 2,
                            Title = "Book_$44"
                        },
                        new
                        {
                            Id = 45,
                            GenreId = 12,
                            PublisherId = 3,
                            Title = "Book_$45"
                        },
                        new
                        {
                            Id = 46,
                            GenreId = 12,
                            PublisherId = 1,
                            Title = "Book_$46"
                        },
                        new
                        {
                            Id = 47,
                            GenreId = 12,
                            PublisherId = 5,
                            Title = "Book_$47"
                        },
                        new
                        {
                            Id = 48,
                            GenreId = 12,
                            PublisherId = 1,
                            Title = "Book_$48"
                        });
                });

            modelBuilder.Entity("Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Genre_1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Genre_2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Genre_3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Genre_4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Genre_5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Genre_6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Genre_7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Genre_8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Genre_9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Genre_10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Genre_11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Genre_12"
                        });
                });

            modelBuilder.Entity("Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Publisher_1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Publisher_2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Publisher_3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Publisher_4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Publisher_5"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.HasOne("Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
